name: ğŸ·ï¸ Create Tag and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  get-version:
    name: âš™ï¸ Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: ğŸ”½ Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Get the current version
        id: get_version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  tag-release:
    name: ğŸ·ï¸ Tag and Release v${{ needs.get-version.outputs.version }}
    needs: get-version
    uses: next-dvalverde/workflow-tag-and-release-version/.github/workflows/tag-and-release.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
